{"name": " Проверяем, что если создать пользователя с логином, который уже есть, возвращается ошибка.", "status": "passed", "start": 1703425132424, "stop": 1703425132814, "uuid": "6cd0485a-4b2c-4e85-abf7-b6f9e78e2e19", "historyId": "20880875acd9b2b60d79b53f502e3adc", "testCaseId": "20880875acd9b2b60d79b53f502e3adc", "fullName": "tests.test_courier_creat.TestCourierCreate#test_create_two_identical_couriers_error_message", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_creat"}, {"name": "subSuite", "value": "TestCourierCreate"}, {"name": "host", "value": "Lenovo-3"}, {"name": "thread", "value": "8488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_creat"}]}